/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GraphicDesignRouteImport } from './routes/graphic-design'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliciesTermsRouteImport } from './routes/policies.terms'
import { Route as PoliciesRefundsRouteImport } from './routes/policies.refunds'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as LocationsKentWaRouteImport } from './routes/locations.kent-wa'
import { Route as ApiContactRouteImport } from './routes/api.contact'

const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicDesignRoute = GraphicDesignRouteImport.update({
  id: '/graphic-design',
  path: '/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundsRoute = PoliciesRefundsRouteImport.update({
  id: '/policies/refunds',
  path: '/policies/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsKentWaRoute = LocationsKentWaRouteImport.update({
  id: '/locations/kent-wa',
  path: '/locations/kent-wa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/industries': typeof IndustriesRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/web-development': typeof WebDevelopmentRoute
  '/api/contact': typeof ApiContactRoute
  '/locations/kent-wa': typeof LocationsKentWaRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/terms': typeof PoliciesTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/industries': typeof IndustriesRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/web-development': typeof WebDevelopmentRoute
  '/api/contact': typeof ApiContactRoute
  '/locations/kent-wa': typeof LocationsKentWaRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/terms': typeof PoliciesTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/industries': typeof IndustriesRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/web-development': typeof WebDevelopmentRoute
  '/api/contact': typeof ApiContactRoute
  '/locations/kent-wa': typeof LocationsKentWaRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/terms': typeof PoliciesTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-automation'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/graphic-design'
    | '/industries'
    | '/marketing'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/web-development'
    | '/api/contact'
    | '/locations/kent-wa'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-automation'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/graphic-design'
    | '/industries'
    | '/marketing'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/web-development'
    | '/api/contact'
    | '/locations/kent-wa'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-automation'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/graphic-design'
    | '/industries'
    | '/marketing'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/web-development'
    | '/api/contact'
    | '/locations/kent-wa'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAutomationRoute: typeof AiAutomationRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  GraphicDesignRoute: typeof GraphicDesignRoute
  IndustriesRoute: typeof IndustriesRoute
  MarketingRoute: typeof MarketingRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
  ApiContactRoute: typeof ApiContactRoute
  LocationsKentWaRoute: typeof LocationsKentWaRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesRefundsRoute: typeof PoliciesRefundsRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic-design': {
      id: '/graphic-design'
      path: '/graphic-design'
      fullPath: '/graphic-design'
      preLoaderRoute: typeof GraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/refunds': {
      id: '/policies/refunds'
      path: '/policies/refunds'
      fullPath: '/policies/refunds'
      preLoaderRoute: typeof PoliciesRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/kent-wa': {
      id: '/locations/kent-wa'
      path: '/locations/kent-wa'
      fullPath: '/locations/kent-wa'
      preLoaderRoute: typeof LocationsKentWaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAutomationRoute: AiAutomationRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  GraphicDesignRoute: GraphicDesignRoute,
  IndustriesRoute: IndustriesRoute,
  MarketingRoute: MarketingRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
  ApiContactRoute: ApiContactRoute,
  LocationsKentWaRoute: LocationsKentWaRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesRefundsRoute: PoliciesRefundsRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
